### ISSUE TITLE
add index into `by` function

### ISSUE THREAD

**Issue by Himself65** [meyfa/group-items#79]
```ts
const keyValues = Object.entries(props.value)
group(keyValues).by((kv, index) => index % x)
```

**Comment by meyfa** [comment]
That's a great suggestion! Would you like to send a pull request to implement this feature? We will also need to update the documentation and add unit test cases. If you're not interested in implementing this, I will probably pick it up at some point - but it could take a while, since I am rather busy right now.

**Comment by meyfa** [comment]
I just had a thought. This feature would be very useful for strings as well. The following example is rather silly, but shows how concise some things become, that would normally be a lot less beautiful to program:

```ts
group('ax1by2cz3')
  .by((s, i) => i % 3)
  .asArrays()
  .map((arr) => arr.join(''))
// result: ['abc', 'xyz', '123']
```

**Comment by Himself65** [comment]
> I just had a thought. This feature would be very useful for strings as well. The following example is rather silly, but shows how concise some things become, that would normally be a lot less beautiful to program:
> 
> 
> 
> ```ts
> 
> group('ax1by2cz3')
> 
>   .by((s, i) => i % 3)
> 
>   .asArrays()
> 
>   .map((arr) => arr.join(''))
> 
> // result: ['abc', 'xyz', '123']
> 
> ```

Yeah, I'm coding like your case

https://github.com/TexteaInc/json-viewer/blob/a18516c081146424ea3e301970cd6bbd71502db0/src/components/DataTypes/Array.tsx#L75

**Comment by Himself65** [comment]
> That's a great suggestion! Would you like to send a pull request to implement this feature? We will also need to update the documentation and add unit test cases. If you're not interested in implementing this, I will probably pick it up at some point - but it could take a while, since I am rather busy right now.

I can help this. Give some time
